### ISSUE TITLE
Is this package still used?

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue_maps#1]
Is this package still used? I thought the maps were now defined in https://github.com/tue-robotics/ed_object_models

**Comment by reinzor** [comment]
That's true, this package is deprecated

**Comment by alberth** [comment]
I implemented reverse dependency resolving between packages, and indeed it's not referenced by any other catkin package. Therefore, it's either a top-level package, or it's obsolete.

I think it would be useful to have a way to get rid of old repositories.
